# Generated by Django 4.0 on 2021-12-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blogpost_slug'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='readed',
            field=models.ManyToManyField(blank=True, related_name='readed', to='blogs.BlogPost'),
        ),
    ]
