version: '3.9'
services:
 web:
   command: python manage.py runserver 0.0.0.0:8005
   build: .
   ports:
    - "8005:8005"
   volumes:
    - .:/app
   links:
    - db
   environment:
    - DEBUG=1
 db:
   image: nouchka/sqlite3:latest
   volumes:
     - ./app/data/db:/root/db
   environment:
     - SQLITE3_DB=db.sqlite3