version: '3.9'
services:
 web:
   build: .
   command: python manage.py runserver 0.0.0.0:8005
   container_name: django_microblog
   volumes:
    - .:/app
   ports:
    - "8005:8005"
   depends_on:
    - db
   environment:
    - DEBUG=1
 db:
   image: nouchka/sqlite3:latest
   volumes:
     - ./app/data/db:/root/db
   environment:
     - SQLITE3_DB=db.sqlite3